---
#deny-all-ingress
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress: []

---
# deny-all-engress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-engress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  # allow port 443
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 27017
      protocol: TCP
    - port: 80
      protocol: TCP
    - port: 5000
      protocol: TCP
    - port: 4200
      protocol: TCP

---
# allow-nginx-ingress-to-accord-namespace
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-nginx-ingress-to-accord-namespace
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {}
  ingress:
    - from:
      - namespaceSelector:     
          matchLabels:
            purpose: nginx-ingress  
        podSelector:           
          matchLabels:
            app.kubernetes.io/name: ingress-nginx

---
# allow-accord-web-to-accord-service
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-accord-web-to-accord-service
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: accord-service
  ingress:
  - ports:
    - port: 5000
    from:
    - podSelector:
        matchLabels:
          app: accord-web

---
# allow-accord-service-to-mongo
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-accord-service-to-mongo
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongo
  ingress:
  - ports:
    - port: 27017
    from:
    - podSelector:
        matchLabels:
          app: accord-service

---
