apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: accord-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    METAACCESS_CLIENT_ID: AgAcRXBiDJ7nfyLKYHP6YZzslrAQdFEYQrwfkU2CUn0aiGLgYgLhIEe3J3nMmUPYvno4FPSRzJ+ojAv3wrp4EhYlqpItEkOShOCPlg/KuAzCH6gXB13zD5urYnIv11UGflHW92Nm/PCfhpvSxl54sbJ0+Y5zL+DE9gaCHdn+ER8yMGSIORlrdZO5iNUfh8+suLn2ZpyZfgET3u/1/6/XLIWLawMaht4f2IVMQe5vt9SoP4ST5a57KWDGYm4CcZOgT5C0j3AVjXQcDDsHID1jCivZSXZN+5qwAtDxcFDzKvXpjIBEusWXSndE4WShq2HjNTc+EK3u/qYlQ+Oi8RBBMKRjgsAdxm67gdFbPvQs1pNhqCg2CRkdkPFhwLIcwz96poA6Oh50FKeonRu3luJFOvpnIVv6sS0w4Q4eNSqLUz8s719ZuyUqWNkbLSOF6hDCjToGYSeyRKlNfbi/W9KtNYzpVHMXR7ZJgCaBDKrivGQ2Z3k8SrmxsYqRmXhumr2WhnBAosHryeECMWIC3TOaaEci7Y/JyLuvfUuyUSJp8lswJaKqzZkGX6ptVYSclGhS4JGsbuAHb83m/c7HlxkWQOcZemnyRAVWyWvf5tcAvSytDNLrjNC8lDyHhASbReWvxwytl+UzzaYg+U/LmyFLCDMlCjP9DKkcHHfouvvgECnWxK08Cnd3ubhYtXF/Z3MIVP8Kd+TM8c9djnAICggBERjLzzqdXLgSQU2aqDc6u5p8+YWEelQe/48e/qhG3cqAYNY=
    METAACCESS_CLIENT_SECRET: AgCOh/1VraFsLBM6YfW0WLl5npxHZOoooYJCvj4yDdMBm7h4RA2eaj4n/SkS7Gbsx6sGSycyBC4jXl63Kcib2iV0PktpBbtIrCquIEFOqcmWDfioF2QMzfUyP2A0eV+zbWMT5bHIAvLXwHP6uzq9jWI7N9xsxePQ3G/Z+P6K5dHzQ5Dc+YHB5/dND1XwV/S/gUhXqjKRt2sO39c2h1Lyxekli46dHjCFakQqefcImOPykX4dbX9ftKR0rWbYW9R8zbovOse69RylEhdxAkKX2WWBeDAwtGPCm5dCoEBBEWMkqZMKBZAOwSeDYpaGl5iGzJK4wM3GFSzVVBFDONVcLa0aclGoaZUwVr2VoCfJOj2epSIaZQCBk8M4HsNjXmqOpYqWLw6q7fOp++5jJfTK/u05+EI4/fOdrJrYFnW9xMSScb/QiLppXAWvo3e6O8iq7rRI2WSkYG8YSlIBWZla6WPXdK5WrNcOcsEUMQr6IeiHRxBBvaGebsBM3eq9C9ay9qyJL4pNXaRXmXLTTcH2eLoHmH1jvhdp7hF9pzOB/CptWZ25N/3zqs8bSDILolQ8THhOX+GsQZg5C+tWBRiTwejNroGccThcC6NmqVy8hM9XnVZ1JpAGs0SDeMIl2ejdGJZHPZRgqg2u4TN6F3piJUde9sxXWaJZig0naEEXKasAukhfWv0r2X6B/a1O+C19ZdUYJeELDwMvD+8P4EflcTI63vOSIyH/nepwAlNTlimYnJ8bMsg7VgvMBSh1PEJJoeI=
  template:
    metadata:
      name: accord-service-secrets
      namespace: {{ .Release.Namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-auth-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_AUTH_TOKEN: AgCTdEpAywsyrvMrCbh4aEZvdkxVT7mDABvMu7/2BdIabuj2LdUO8eySjUPYBBXuQEh1chfm/W3YnvDOQ8X54/LUYNt4z2EYajP3uy5CMgmceS1R2xx0Wymy2kxm3x99hK4muJr9hKa97IMir+KxvDVXKPJSmrBq4Xg8ZkbUufbJ2HWVYcGtof9KuUr+KusvoKVbKhAys0ap7pLz0S7giWZhYctJ2F27j2bDv+EJVQvSEWAxLI5OlkJrwRJf1Zy3hQ+9thMDrImRWB6bp3Tsc73DLCEXc1j7lMawGp3o6Cpqy3kg5T3emFesGkB+cLXy8e0uFt6Lo/POTQUAEfO9DP19gP09iW55OlbDzCMhe8b/d0zt1C2cf5bsY1YSkBljSggVDsM1b3kULS2bzNChmTMsdsEaGeyegs9fRYGkuL6vWfMPS3bShI6+awcG2ocqeYx+v4mzxwCmd0Ng8fATATk7HBQCbtbpP+IS07Ow21mkjitCAiOL47g93aCeTC9faVxU7eAorv0Tk+dQJjOEgUhT3w11OUZIWtDsi7P9ZxDjrkm1zXEmwCJUyqTy/8IURa4IVmmiyDE99Zka+9kRRsHRlHdsvVzkVGWOyruqn6+JN44obimLaviwV+BUSBPuaval5LqgUfTdK70jjhWquvLvulQj2vOJdg80iWUggutsytcMIiG+xus4Icmuj+UWvNbCX+8pQez6Ta+6hCYj/q9lT6FSpChMJ/HJv65R3mlVbCuYGsSwkOYo9hPe7A==
  template:
    metadata:
      name: jwt-auth-secret
      namespace: {{ .Release.Namespace }}
