apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: accord-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    METAACCESS_CLIENT_ID: <set them for prod>
    METAACCESS_CLIENT_SECRET: <set them for prod>
  template:
    metadata:
      name: accord-service-secrets
      namespace: {{ .Release.Namespace }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-auth-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_AUTH_TOKEN: AgBJmzUgZ0vTYHUXJE4BGJ/wRNgsGB/r3HqYqhysTONGiGe2D4M299TXTkhElocCX6jFH9gCdhVsXbt0eJtREidJGrW+i2j+FE+XhDmI5QaKpiLSKeVUrFgA1NSODGKt1Qc4Meqc7IeJXv4VodIPm4R/k+FXNnjkloJMwnACZkI3v5Cn1S5tpC6eYDGqd+fo7RDLCgIjhe/fKq2ItwSnsBaIepdc3Ljh11jxGOezezsbSoL1egmC1u5OoqrKbZR6uDFT70ifwvOftcA8H2CtZbnXs1WxSfrtUfJzrqIEt3FR9Hm6iDJkdtE/2d5JimiXwkVH0SBzUxU7Mjim03D2sBJV5xc2p07spbeKSzgJFOvvSc8o5KTOkLLuBVrnMw3kZLhS46znGApRQD5rNGxTDkyypWL/mgvSa/4bt46L8w3aP7YJriolhDUGRUS5ZlDbs/F4AJgxJy9C/M5LXGfNpvTxib+xwAvQWWV2aJOQMskwv8uCUObqroTTDrc+ux78Iue2K36WUKW1DUuvaVpZf1Q+GPcovkk4DjsmHNSSxg5lpjc0bklbOe7UotofVAFYyUO8gQC+z6fgDUsGSLdyXmRGd/jOpB6Qtrqj9xRKir/cSbtKK/AVO+IS7iiGOKqxnFlldzaofRNAA19EUJr2TQKa42uCsmWh5iVTHypDpyQLbtrG/4iBpfcQb/IHAELXBjL3ytWtKefehGe3RYnvFpHnANkGq6l+nWIEZs29PK7h8RcRsiya9rGsUsL35A==
  template:
    metadata:
      name: jwt-auth-secret
      namespace: {{ .Release.Namespace }}
