---
# accord-web assets configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: accord-web-assets-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
     "production": false,
     "api": "https://{{ .Values.envUrl }}.{{ .Values.appDomain }}/accord/api/"
    }
---
# accord-web deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accord-web
  name: accord-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accord-web
  template:
    metadata:
      labels:
        app: accord-web
    spec:
      containers:
      - image: "{{ .Values.images.accord_web.repository }}:{{ .Values.images.accord_web.tag }}"
        name: accord-web
        imagePullPolicy: "{{ .Values.images.accord_web.pullPolicy }}"
        volumeMounts:
        - name: accord-web-assets-config
          mountPath: /usr/share/nginx/html/assets/config
      volumes:
      - name: accord-web-assets-config
        configMap:
          name: accord-web-assets-config
---
# accord-web service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accord-web
  name: accord-web-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "accord-web-port"
      port: 80
      protocol: TCP
      targetPort: 4200
  selector:
    app: accord-web
---
# accord-web ingress definition
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: accord-web
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: "{{ .Values.envUrl }}.{{ .Values.appDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: accord-web-service
          servicePort: 80
