# Application definition for doing "in situ" development
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}-userpods
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: userpods/templates
    repoURL: https://github.com/uvarc/accord-container-dev.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
